// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"Basic plugin for manipulating important parameters.","parameters":{"cacheLimit":"20","screenWidth":"816","screenHeight":"624","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"auto","alwaysDash":"off"}},
{"name":"MadeWithMv","status":true,"description":"Show a Splash Screen \"Made with MV\" and/or a Custom Splash Screen before going to main screen.","parameters":{"Show Made With MV":"true","Made with MV Image":"MadeWithMv","Show Custom Splash":"false","Custom Image":"","Fade Out Time":"120","Fade In Time":"120","Wait Time":"160"}},
{"name":"自动战斗插件","status":true,"description":"自动战斗插件，在战斗界面有一个选项可以使你的人物自动战斗，而不必自己每次选择战斗方式！","parameters":{"PartyCommandName":"自动","PartyCommandIndex":"-1","ActorCommandName":"自动","ActorCommandIndex":"-1","AffectedStrongBindState":""}},
{"name":"云雾系统插件","status":true,"description":"云雾系统添加","parameters":{"Label":"fog"}},
{"name":"日志显示插件","status":true,"description":"自动战斗插件，在战斗界面有一个选项可以使你的人物自动战斗，而不必自己每次选择战斗方式！","parameters":{"PartyCommandName":"Auto"}}
];
